language: c
sudo: required
os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install gcc --enable-fortran || true;
      brew link --overwrite gcc;
    fi
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh

env:
  global:
    - PACKAGE=lbfgs
  matrix:
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.04

notifications:
  email:
    - Christophe.Troestler@umons.ac.be
