language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam
    - gfortran

script: bash -ex .travis-opam.sh
env:
  - OPAM_SWITCH=system
  - OPAM_SWITCH=3.12.1
  - OPAM_SWITCH=4.01.0
  - OPAM_SWITCH=4.02.2
cache:
  directories:
  - $HOME/.opam
