language: c
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - gfortran

script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.02
cache:
  directories:
  - $HOME/.opam

notifications:
  email:
    - Christophe.Troestler@umons.ac.be
