language: c
sudo: required
os:
  - linux
  - osx

# brew looks quite broken...
matrix:
  allow_failures:
    - os: osx

install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh

env:
  global:
    - PACKAGE=lbfgs
  matrix:
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.04

notifications:
  email:
    - Christophe.Troestler@umons.ac.be
